### ISSUE TITLE
Missing link between Session - Management and UI

### ISSUE THREAD

**Issue by sharanya17410** [airavata-courses/NSA#100]
The session management and UI are not communicating properly. There seems to be a missing link , I do not see the result of the launched job in the results page. The values in the page were not getting full populated and it wasn't dynamically updating the status of the jobs launched.
![WhatsApp Image 2020-03-20 at 7 19 38 PM](https://user-images.githubusercontent.com/46901933/77213089-f3dfc080-6adf-11ea-8e84-cb0f2ad46bd7.jpeg)

**Comment by aniruddhavpatil** [comment]
a015771 fixes this.
