### ISSUE TITLE
System Architecture Diagram

### ISSUE THREAD

**Issue by aniruddhavpatil** [airavata-courses/NSA#21]
![nsa_system_diagram](https://user-images.githubusercontent.com/15905232/74046768-23f25a80-499d-11ea-95c1-7de0d6537210.png)

A basic architecture diagram. Let's discuss to make corrections/changes and add more details.

**Comment by nbafna04** [comment]
We are no longer considering gRPC for microservice communication, as Kafka handles this internally through its own protocols. The reason to go ahead with Kafka and not use gRPC is to reduce coupling.

**Comment by aniruddhavpatil** [comment]
![nsa_system_diagram (2)](https://user-images.githubusercontent.com/15905232/74502599-fab15d00-4ebb-11ea-8b61-5338612e653b.png)
