### ISSUE TITLE
Dockerize data-retrieval

### ISSUE THREAD

**Issue by aniruddhavpatil** [airavata-courses/NSA#27]
- https://docs.docker.com/get-started/part2/
- https://docs.docker.com/develop/develop-images/dockerfile_best-practices/
- https://docs.docker.com/compose/gettingstarted/
- https://runnable.com/docker/python/dockerize-your-python-application

**Comment by aniruddhavpatil** [comment]
- https://github.com/wurstmeister/kafka-docker/wiki/Connectivity

**Comment by nbafna04** [comment]
Task completed
