### ISSUE TITLE
Fix master-slave sync issues on Jetstream

### ISSUE THREAD

**Issue by aniruddhavpatil** [airavata-courses/NSA#57]

**Comment by JShivali** [comment]
useful article: https://github.com/kubernetes-sigs/kubespray/issues/5303#

**Comment by Novitoll** [comment]
Install chrony or NTP like on each master server and sync to each other.
https://github.com/kubernetes-sigs/kubespray/issues/5303#issuecomment-597472483

**Comment by JShivali** [comment]
No need of using Chrony. Figured out that I was using the TACC cluster and hence faced this issue.
