### ISSUE TITLE
Checklist - Assignment 1

### ISSUE THREAD

**Issue by nbafna04** [airavata-courses/NSA#8]
1. UI / Web Service
2. API gateway
3. User management service
4. Session management service
5. Data Retrieval service
6. Model mock up service
7. Post processing service
8. 3 different languages
9. Different DB for each service if required(No two services should access same Database)
10. User authentication. (User audit)
11. Service calls though message handlers
12. Continuous Integration and deployment system for deploying the services.
13. System independent application.
14. Easily deployable.

**Comment by JShivali** [comment]
Adhered to checklist
